# Generated by Django 3.2.7 on 2022-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='action_books',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='contemporary_books',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='fantasy_books',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='fiction_books',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='thriller_books',
            field=models.BooleanField(default=False),
        ),
    ]
