# Generated by Django 3.2.7 on 2022-04-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20220428_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fiction_books',
            new_name='comic_books',
        ),
    ]
