# Generated by Django 3.2.7 on 2022-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20220428_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='book',
            field=models.ManyToManyField(blank=True, default=False, to='shelf.Book'),
        ),
    ]
