# Generated by Django 3.2.7 on 2022-04-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_auto_20220428_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='book',
        ),
        migrations.CreateModel(
            name='Shelved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.book')),
                ('bookshelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.bookshelf')),
            ],
        ),
        migrations.CreateModel(
            name='Archived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.archive')),
                ('shelved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.shelved')),
            ],
        ),
    ]
