# Generated by Django 3.2.7 on 2022-04-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0008_auto_20220429_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userName',
            new_name='username',
        ),
    ]
