# Generated by Django 3.2.7 on 2022-04-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0009_rename_username_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived',
            name='archive',
        ),
        migrations.AddField(
            model_name='archived',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shelf.book'),
        ),
    ]
